// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zpmzwerqqwewzomqyvad.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpwbXp3ZXJxcXdld3pvbXF5dmFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyNzU5NzcsImV4cCI6MjA2OTg1MTk3N30.6O5lc6BHbuoJd4Re8gpm3G4Po3npwpDBHPeMGyEOLvk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});